<?xml version="1.0"?>
<package format="2">
    <name>imgo2_description</name>
    <version>0.0.0</version>
    <description>imgo2 robot description files</description>
    <maintainer email="TODO@gmail.com">Qiayuan Liao</maintainer>
    <license>BSD</license>
    <author email="TODO@gmail.com">Qiayuan Liao</author>

    <!-- buildtool_depend: dependencies of the build process -->
    <buildtool_depend>catkin</buildtool_depend>
    <exec_depend>xacro</exec_depend>
    <exec_depend>joint_state_publisher</exec_depend>
    <exec_depend>robot_state_publisher</exec_depend>

</package>
